site_name: Categorical Pose and Shape Evaluation
site_url: https://roym899.github.io/pose_and_shape_evaluation/
repo_url: https://github.com/roym899/pose_and_shape_evaluation
repo_name: roym899/pose_and_shape_evaluation
theme: 
  name: material
  icon: 
    repo: fontawesome/brands/github

extra_css:
  - css/mkdocstrings.css

plugins:
  - search
  - mkdocstrings:
      watch:
        - cpas_toolbox
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_signature_annotations: true
            show_source: true
            separate_signature: True
            docstring_section_style: "spacy"
            line_length: 75
            members_order: source
          selection:
            docstring_style: "google"
            members: no
      enable_inventory: true

nav:
  - Getting started: index.md
  - Data preparation: data_preparation.md
  - API Reference:
    - evaluate.py: api_reference/evaluate.md
    - datasets:
      - nocs_dataset.py: api_reference/datasets/nocs_dataset.md
      - nocs_utils.py: api_reference/datasets/nocs_utils.md
      - redwood_dataset.py: api_reference/datasets/redwood_dataset.md
    - cpas_methods:
      - cass.py: api_reference/cpas_methods/cass.md
      - spd.py: api_reference/cpas_methods/spd.md
      - crnet.py: api_reference/cpas_methods/crnet.md
      - asmnet.py: api_reference/cpas_methods/asmnet.md
    - metrics.py: api_reference/metrics.md
    - cpas_method.py: api_reference/cpas_method.md
    - camera_utils.py: api_reference/camera_utils.md
    - pointset_utils.py: api_reference/pointset_utils.md
    - quaternion_utils.py: api_reference/quaternion_utils.md
    - utils.py: api_reference/utils.md
