# All baselines
config:
  methods:
    cass: ./cass.yaml
    spd: ./spd.yaml
    crnet: ./crnet.yaml
    sgpa: ./sgpa.yaml
    # asmnet: ./asmnet.yaml  # weights not available anymore
    icaps: ./icaps.yaml
    sdfest: ./sdfest.yaml
    dpdn: ./dpdn.yaml
    rbppose: ./rbppose.yaml
