name: ASMNet
wrapper_type: cpas_toolbox.method_wrappers.ASMNetWrapper
config_dict:
  models_folder: ~/.cpas_toolbox/models/asmnet/weights/
  asm_params_folder: ~/.cpas_toolbox/models/asmnet/asm_params/
  categories: ["bottle", "bowl", "camera", "can", "laptop", "mug"]
  deformation_dimension: 3
  num_points: 800
  use_mean_shape: False
  use_icp: True
  device: cuda
