name: CASS
wrapper_type: cpas_toolbox.method_wrappers.CASSWrapper
config_dict:
  num_points: 500  # points in reconstructed pointcloud
  num_objects: 6  # number of categories
  model: ~/.cpas_toolbox/models/cass/cass_best.pth
  device: cuda
