name: SPD
wrapper_type: cpas_toolbox.method_wrappers.SPDWrapper
config_dict:
  num_categories: 6
  num_shape_points: 1024 
  num_input_points: 1024
  image_size: 192
  model: ~/.cpas_toolbox/models/spd/model_50.pth
  mean_shape: ~/.cpas_toolbox/models/spd/mean_points_emb.npy
  device: cuda
