name: PyTest

env:
  SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True

on:
  push:
    branches-ignore:
      - docs
  pull_request:
    branchest-ignore:
      - docs
 
jobs:
  pytest_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9" ]
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install prerequisites
      run:
        pip install .
        pip install pytest
    - name: Run pytest
      run: |
        pytest -rf tests/
